### ISSUE TITLE
[TASK] New "TBRN Space" Theme

### ISSUE THREAD

**Issue by bambiemurphyuk** [TBRN-ORG/Website#13]
**URL**
Not Applicable

**Summary of task**
Creation of a new website Theme and Styles.

**Task to-do list**

_**Theme**_

- [ ] Creation and mockup of the new theme named "TBRN Space"

_**Styles**_

- [ ] Daylight v1
- [ ] Daylight v1 (Full Width)
- [ ] Night v1
- [ ] Night v1 (Full Width)

**Additional context**
This is in connection to #10 Logo Overlapping. This will be fixed with the new site theme.
